### ISSUE TITLE
bring back support for tables

### ISSUE THREAD

**Issue by odinuv** [keboola/sapi-python-client#22]

**Comment by odinuv** [comment]
do #24 first

**Comment by pivnicek** [comment]
@odinuv cheers for making these issues.  Just curious what does it mean to "bring back support for tables"?

**Comment by pivnicek** [comment]
Sorry, I just looked through the `dev` branch and understand what this means now:)  dik!

**Comment by odinuv** [comment]
i'm working on it already

**Comment by odinuv** [comment]
done in 718b88178ff175e55213a44068160b8ca9cdfe08
