### ISSUE TITLE
Implement the Client class

### ISSUE THREAD

**Issue by pocin** [keboola/sapi-python-client#29]
as discussed in some comments floating somewhere around here. The client would handle passing of the `base_url` and `auth_token` to the endpoints + bundle all the endpoints to one place so we are left with this simple and clean usage:

```python
>>> from kbcstorage import Client
>>> client = Client('myapitoken')
>>> client = Client('myapitoken', root_url='https://connection.keboola.com') # alternatively 
>>> client.buckets.list()
# a list of all buckets
>>> client.workspaces.detail(1234)
# etc...
```

This still allows one to instantiate endpoints one by one if he wishes to.

```python
from kbcstorage.tables import Tables
from kbcstorage.buckets import Buckets

tables = Tables('https://connection.keboola.com', 'your-token')
# get table data into local file
tables.export_to_file(table_id='in.c-demo.some-table', path_name='/data/')
# save data
tables.create(name='some-table-2', bucket_id='in.c-demo', file_path='/data/some-table')
# list buckets
buckets = Buckets('https://connection.keboola.com', 'your-token')
buckets.list()
# list bucket tables
buckets.list_tables('in.c-demo')
# get table info
tables.detail('in.c-demo')
```

I am happy to implement this after we deal with #28

**Comment by odinuv** [comment]
yep, that looks like something i imagined :)

**Comment by Ogaday** [comment]
ed2400d removed the `Client` class which did exactly this?

**Comment by odinuv** [comment]
Uh, sorry about that, I sort of came to conclusion that it's only a stub.

**Comment by odinuv** [comment]
I'll put it back in a moment

**Comment by Ogaday** [comment]
No worries, most of the functionality is in the endpoints anyway. I like the client structure to tie them all together but currently it's also possible to have endpoints instantiated independently anyway.

I would say only two changes need to be made:

* [ ] Choose the argument order: I prefer url first then token, but I'd happily concede if there is a preference for the converse.
* [ ] Use the python properties pattern to make it possible to change the password post instantiation.

Unless there are any other changes, I could quickly make those changes and we could close this issue?

**Comment by odinuv** [comment]
actually @pivnicek already merged that https://github.com/keboola/sapi-python-client/pull/31/files (slightly before i expected) - the arguments are consistent i think 

I don't understand the second point though

**Comment by odinuv** [comment]
2nd point solved in https://github.com/keboola/docker-custom-python/commit/fbda9b4ccfdf96feb8cec83d54cc75bd2e1c9c24 -> Client class finished
