### ISSUE TITLE
Tables exported to csv have wrong headers when specific columns are selected

### ISSUE THREAD

**Issue by hrubanj** [keboola/sapi-python-client#61]
Hi,
I believe I have spotted a bug in the export_to_file() method of the Tables class.
The exported csv always gets headers based on all columns of the table even if I select only a subset of them. Moreover, the order of header labels is based purely on the table detail in KBC, even though they might be exported in different order based on the columns argument.
I think this could be fixed if you used columns from table detail only as a fallback to handle situations where columns are not specified by the user. I.e. by replacing line 422 in kbcstorage/tables.py by this:
```python
            if columns is None:
                columns = table_detail['columns']
```

**Comment by pivnicek** [comment]
Thanks @hrubanj !  Please feel free to make a pull request if you need this quickly 😄

**Comment by pivnicek** [comment]
Sorry for the delay @hrubanj , it's been resolved now.  Thanks again for reporting it.
