### ISSUE TITLE
Polling job status sleep time

### ISSUE THREAD

**Issue by hrubanj** [keboola/sapi-python-client#64]
Hello guys,
I believe there is a minor bug in the computation of sleep time between successive API calls.
The _retries_ variable does not get incremented and therefore the sleep time is always 2 seconds.
This does not impact me in any significant way. I just noticed that this might not have been the original intention and wanted to let you know.

https://github.com/keboola/sapi-python-client/blob/5a93926c2191ccd6b7402c9e24d9912884d87d4c/kbcstorage/jobs.py#L100-L121

**Comment by odinuv** [comment]
Hi,
thanks for pointing this out, you're completely right. We'll fix that in the coming weeks.

**Comment by odinuv** [comment]
resolved in https://github.com/keboola/sapi-python-client/pull/65
