### ISSUE TITLE
Travis build and deploy

### ISSUE THREAD

**Issue by odinuv** [keboola/sapi-python-client#9]

**Comment by odinuv** [comment]
Fixed in 4d91bfd1ef1f4da3005a8a1f99333c464477d422

**Comment by Ogaday** [comment]
I haven't worked with CI before - does it change my contribution workflow? Should I merge the travis PR into my fork? Or will Travis just be triggered when I submit a PR to this repo?

**Comment by odinuv** [comment]
no it does not really change the workflow it will tests PR automatically, the results are here https://travis-ci.org/keboola/sapi-python-client, but you should merge latest master to your branch so that it triggers automatically
